### ISSUE TITLE
Morning Code Review

### ISSUE THREAD

**Issue by StarSheriff2** [brenoxav/nyt-clone-microverse#1]

**Comment by marcelomaidden** [comment]
Great job in your way of work. I see you start doing the html structure and after that apply css, so congratulations.
My only suggestion is instead of using an article for the grid images on footer part using an aside, only for html semantics.

**Comment by carloso0114** [comment]
its nicely done, cant wait to see how it will look like when you css style it!

**Comment by StarSheriff2** [comment]
> Great job in your way of work. I see you start doing the html structure and after that apply css, so congratulations.
> My only suggestion is instead of using an article for the grid images on footer part using an aside, only for html semantics.



> Great job in your way of work. I see you start doing the html structure and after that apply css, so congratulations.
> My only suggestion is instead of using an article for the grid images on footer part using an aside, only for html semantics.

Changed the HTML tag Article in the bottom to Aside. Thanks!
